#! /bin/bash

# This script looks for enhancer-relevant bam-files in a given directory, writes them to CRUP-readable data tables and returns a list of those files

[[ $# != 3 ]] && echo "Usage: prun mdl create_crup_datatable sample outfile h3k27ac.bam h3k4me1.bam h3k4me3.bam" && exit 1

# parse arguments and initialize variables
sample=$1
outfile=$2
h3k27ac=$3
h3k4me1=$4
h3k4me3=$5

# stop if any file for this replicate was not found
for fn in ${files[@]}; do
	[ -z $fn ] && echo "Error: Not all necessary bam-files were found at $bam_dir" && exit 1
done

# write data table
echo -e "feature\tbam_file" > $outfile
echo -e "H3K27ac\t${h3k27ac}" >> $outfile
echo -e "H3K4me1\t${h3k4me1}" >> $outfile
echo -e "H3K4me3\t${h3k4me3}" >> $outfile
